# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-12 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_editor',
            field=models.BooleanField(default=False, verbose_name=False),
        ),
    ]
