# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-17 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='schedule',
            field=models.ImageField(blank=True, null=True, upload_to='taskList_photos', validators=[utils.validators.validate_file_size, utils.validators.validate_extension]),
        ),
    ]
